name: E2E site testing

on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  e2e-current:
    name: e2e current latest branch
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-ver: ["3.11", "3.12"]
        os: [ubuntu-latest]
        # os: [self-hosted-arm64, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # Setup Docker caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Docker/images-tag.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Load cached Docker images
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: |
          docker load < /tmp/.buildx-cache/images.tar || true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: header
        run: |
          echo -e "\e[1;33m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\e[0m
          \e[1;33m┃\e[0m \e[1;36m E2E Test \e[0m \e[1;33m┃\e[0m
          \e[1;33m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\e[0m"

      - name: install frappe from current commit
        run: |
          cd ..
          python -m pip install --upgrade ./Frappe-Manager

      - name: frappe version
        run: fm --version

      - name: e2e run
        timeout-minutes: 20
        working-directory: test
        run: |
          ./e2e_test.sh

      - name: Upload FM logs
        if: always()  # Upload logs whether the test succeeds or fails
        uses: actions/upload-artifact@v4
        with:
          name: fm-logs-${{ matrix.python-ver }}
          path: ~/frappe/logs/fm.log
          retention-days: 2

      # Save Docker images before cleanup
      - name: Save Docker images
        if: always()
        run: |
          mkdir -p /tmp/.buildx-cache
          docker save $(docker images -q) > /tmp/.buildx-cache/images.tar || true

      - name: cleanup
        if: always()
        run: |
          python -m pip uninstall -y frappe-manager
          sudo rm -rf ~/frappe
